import uuid
from datetime import datetime
from sqlalchemy import String, Boolean, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    """Base class for all ZITRON database models."""
    pass

class Doctor(Base):
    __tablename__ = "doctors"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    employee_id: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    full_name: Mapped[str] = mapped_column(String(100))
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    hashed_password: Mapped[str] = mapped_column(String(255))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    analyses: Mapped[list["AnalysisRecord"]] = relationship(back_populates="doctor")

class AnalysisRecord(Base):
    """
    Core data unit of the ZITRON pipeline.
    Implements a strict decoupled tracking ID pattern. 
    NO patient PII touches this table structure.
    """
    __tablename__ = "analysis_records"

    # Shared Unique ID grouping across backend, inference engine, and dashboard
    tracking_id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    doctor_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("doctors.id"), index=True)
    
    # Secure storage paths for de-identified assets
    anonymized_scan_path: Mapped[str] = mapped_column(String(512), unique=True)
    
    # Bounding parameters generated by Model 1 (CNN/ViT Perception Layer)
    detection_bounding_boxes: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    
    # Diagnostic text report compiled by Model 2 (Quantized Local Medical LLM)
    generated_report_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Pipeline execution state tracking for resource monitoring
    pipeline_status: Mapped[str] = mapped_column(String(30), default="QUEUED") # QUEUED, PROCESSING, SUCCESS, FAILED
    execution_time_seconds: Mapped[float | None] = mapped_column(nullable=True)
    
    # Active learning doctor verification toggle
    # Logged cases into this table establish the offline review pool database table
    clinician_verified: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    clinician_feedback_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    doctor: Mapped["Doctor"] = relationship(back_populates="analyses")